version: '3'

services:
  # api:
  #   container_name: api
  #   build: .
  #   env_file:
  #     - .env
  #   environment:
  #     - DB_ADDRESS=mongo
  #   ports:
  #     - 8000:8000

  db:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
